Fix FTBFS: time crate E0282 with rustc 1.80+
The vendored time 0.3.34 crate fails to compile with rustc >= 1.80
(rustc 1.81 in the build chroot):

  error[E0282]: type annotations needed for `Box<_>`
    --> .../time/src/format_description/parse/mod.rs:83:9
     = note: this is an inference error on crate `time` caused by an
       API change in Rust 1.80.0; update `time` to version `>=0.3.35`

The .map(|res| res.map(Into::into)) introduces an ambiguous Into
conversion that Rust 1.80+ can no longer infer. Upstream time 0.3.35
fixed this by simply removing the redundant map call. This patch
backports that one-line fix to the vendored 0.3.34 source.